# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dependency-injection-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dependency-injection-swift
  pod 'Swinject'
  pod 'AlamofireImage', '~> 4.3'
end
